CITY_STATE_CHOICES = [
    ("Andaman and Nicobar Islands", (("Port Blair", "Port Blair")),),
    (
        "Andhra Pradesh",
        (
            ("Visakhapatnam", "Visakhapatnam"),
            ("Vijayawada", "Vijayawada"),
            ("Guntur", "Guntur"),
            ("Nellore", "Nellore" "),),"),
            ("Kurnool", "Kurnool" "),),"),
            ("Rajamahendravaram" "),," "),Rajamahendravaram"),
            ("Tirupati", "Tirupati"),
            ("Kadapa", "Kadapa"),
            ("Kakinada", "Kakinada"),
            ("Anantapur", "Anantapur"),
            ("Vizianagaram", "Vizianagaram"),
            ("Eluru", "Eluru"),
            ("Ongole", "Ongole"),
            ("Nandyal", "Nandyal"),
            ("Machilipatnam", "Machilipatnam"),
            ("Adoni", "Adoni"),
            ("Tenali", "Tenali"),
            ("Proddatur", "Proddatur"),
            ("Chittoor", "Chittoor"),
            ("Hindupur", "Hindupur"),
            ("Bhimavaram", "Bhimavaram"),
            ("Madanapalle", "Madanapalle"),
            ("Guntakal", "Guntakal"),
            ("Srikakulam", "Srikakulam"),
            ("Dharmavaram", "Dharmavaram"),
            ("Gudivada", "Gudivada"),
            ("Narasaraopet", "Narasaraopet"),
            ("Tadipatri", "Tadipatri"),
            ("Tadepalligudem", "Tadepalligudem"),
            ("Amaravati", "Amaravati"),
            ("Chilakaluripet", "Chilakaluripet"),
        ),
    ),
    (
        "West Bengal",
        (
            ("Kolkata", "Kolkata"),
            ("Asansol", "Asansol"),
            ("Siliguri", "Siliguri"),
            ("Durgapur", "Durgapur"),
            ("Bardhaman", "Bardhaman"),
            ("Malda", "Malda"),
            ("Baharampur", "Baharampur"),
            ("Habra", "Habra"),
            ("Jalpaiguri", "Jalpaiguri"),
            ("Kharagpur", "Kharagpur"),
            ("Shantipur", "Shantipur"),
            ("Dankuni", "Dankuni"),
            ("Dhulian", "Dhulian"),
            ("Ranaghat", "Ranaghat"),
            ("Haldia", "Haldia"),
            ("Raiganj", "Raiganj"),
            ("Krishnanagar", "Krishnanagar"),
            ("Nabadwip", "Nabadwip"),
            ("Midnapore", "Midnapore"),
            ("Balurghat", "Balurghat"),
            ("Basirhat", "Basirhat"),
            ("Bankura", "Bankura"),
            ("Chakdaha", "Chakdaha"),
            ("Darjeeling", "Darjeeling"),
            ("Alipurduar", "Alipurduar"),
            ("Purulia", "Purulia"),
            ("Jangipur", "Jangipur"),
            ("Bangaon", "Bangaon"),
            ("Cooch Behar", "Cooch Behar"),
            ("Bolpur", "Bolpur"),
            ("Kanthi", "Kanthi"),
        ),
    ),
]

